name: Puid Dev

on:
  push:
    branches: [ dev ]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive        

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v
