name: Puid Tests

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test --enable-code-coverage -v --filter PuidTests

      - name: Coverage Report
        run: xcrun llvm-cov export -format="lcov" .build/debug/PuidPackageTests.xctest/Contents/MacOS/PuidPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

      - name: Upload Report
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage_report.lcov
          verbose: true
